postgres:
    image: gaocegege/postgres:9
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password

writer:
    image: gaocegege/hackys-writer:latest
    ports:
    - "8088:8088"
